# Generated by Django 3.2.5 on 2021-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('likes', models.IntegerField()),
                ('poster', models.TextField()),
            ],
        ),
    ]
