# Generated by Django 3.2.5 on 2021-07-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_post_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedBy',
        ),
    ]
